## Binary class Classification

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
iris_data = load_iris()
iris_df = pd.DataFrame(iris_data['data'], columns = iris_data['feature_names'])
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [2]:
target_names = iris_data['target_names']
target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [3]:
# iris_data['DESCR']
iris_df['target_kind'] = iris_data['target']
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target_kind  
0            0  
1            0  
2            0  
3            0  
4            0

In [4]:
X = iris_data['data'][:, 3:] # considering petal width 

In [5]:
Y = (iris_data["target"] == 2).astype(np.int) # making prediction for 2nd type 

In [6]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X, Y)

C:\Users\rgukt\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [7]:
log_reg.predict([[3.2], [1.5]]) # predicting the type based on petal width

array([1, 0])

In [8]:
X_new = np.linspace(0, 3, 30).reshape(-1, 1) # creating petal-widhts 
#X_new

In [9]:
Y_proba = log_reg.predict_proba(X_new) # returns probability of chance having not virginica & virginica
#Y_proba

In [10]:
import matplotlib.pyplot as plt
plt.plot(X_new, Y_proba[:, 1], 'r-', label = "Iris Virginica")
plt.plot(X_new, Y_proba[:, 0], 'b--', label = "Not Iris Virginica")
plt.xlabel("petal width (cm)")
plt.ylabel("Probability")
plt.legend(loc = "lower left")
plt.show()

<Figure size 640x480 with 1 Axes>

## Multi-class  Classification

In [11]:
A = iris_data['data'][:, (2, 3)] # petal length, petal width
B = iris_data['target']

In [12]:
softmax_reg = LogisticRegression(multi_class = "multinomial", solver = "lbfgs", C = 10)

In [13]:
softmax_reg.fit(A, B)

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
softmax_reg.predict([[5, 2], [2, 1]])

array([2, 0])

In [15]:
B_proba = softmax_reg.predict_proba([[0.2, 4.2]])
B_proba

array([[9.99985708e-01, 1.37557306e-05, 5.35841441e-07]])